spring.application.name=projet-service
server.port=8087

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
eureka.instance.hostname=localhost

spring.datasource.url=jdbc:mysql://localhost:3306/cityvoice_projet
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


# Stripe
stripe.secret.key=${STRIPE_SECRET_KEY}
stripe.publishable-key=pk_test_51THXOYF4aoGoerr92O4Dli5iEsaOIMr3Dyk4Uqo9v8vfaki4WTa4sBWVG3PdNtkFA6JQrPddc7x4Z9zwuQ3yKnwp00GHstbhLc
stripe.success-url=http://localhost:4200/projets/payment/success
stripe.fail-url=http://localhost:4200/projets/payment/fail

#ai gemini gemini.api-key=AIzaSyAi6LKwKbN9LPO-Pq1Ib_4ssG1wTtRqyyg

# Ollama
ollama.base-url=http://localhost:11434
ollama.model=qwen3:8b
ollama.vision-model=qwen3-vl:8b

#twilio
twilio.account.sid=${TWILIO_ACCOUNT_SID}
twilio.auth-token=054860b3d6df04616c2c3d4ea70ddc9e
twilio.messaging-service-sid=MG9b6e173e9f139e11662067c635ff61f9 

# User service
userservice.url=http://localhost:8081

#kconnect
konnect.api-key=69e383d2cd2bd9f6adc1769c:86uiUhk0d4YStCllNgausAuWdJ
konnect.wallet-id=69e383d6cd2bd9f6adc176ba
konnect.base-url=https://api.preprod.konnect.network/api/v2
konnect.webhook-url=http://localhost:8080/api/konnect/webhook
konnect.success-url=http://localhost:4200/projets/payment/success
konnect.fail-url=http://localhost:4200/projets/payment/fail

#mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=amineboyka361@gmail.com
spring.mail.password=zukt xyer yozo zcip
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000