spring.application.name=user-service
server.port=8081

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
eureka.instance.hostname=localhost

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/cityvoice_user
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Mail (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rebhiislem800@gmail.com
spring.mail.password=buyt acwz bcwh jwbm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# App config
app.frontend.url=http://localhost:4200
app.reset-token.expiry-minutes=30
# OAuth2
app.oauth2.redirect-uri=http://localhost:4200/auth/oauth2/callback

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=708809148864-3vgl3squpdptt0go0unq79njnqhci3go.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8081/login/oauth2/code/google

# Facebook OAuth2
spring.security.oauth2.client.registration.facebook.client-id=1479241710415702
spring.security.oauth2.client.registration.facebook.client-secret=8478e44ad00fba8450da0457b8d60fa9
spring.security.oauth2.client.registration.facebook.scope=public_profile
spring.security.oauth2.client.registration.facebook.redirect-uri=http://localhost:8081/login/oauth2/code/facebook
spring.security.oauth2.client.provider.facebook.user-info-uri=https://graph.facebook.com/me?fields=id,name,email,picture

# photo
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.mvc.pathmatch.use-suffix-pattern=false

# Spring
spring.mvc.async.request-timeout=60000

# API AI
groq.api.key=${GROQ_API_KEY}
groq.api.url=https://api.groq.com/openai/v1/chat/completions

# API PHOTO
vision.api.key=AIzaSyAirGoAVjROI8olfgzHMk_Xjs5nMkNtB0c
vision.api.url=https://vision.googleapis.com/v1/images:annotate

# Notification
notification.service.url=http://signalement-service:8082

# Photo Moderation ML Service
services.ml.photo-moderation.url=http://localhost:8003

# Churn ML Service
services.ml.churn.url=http://localhost:8001

