spring.application.name=ressource-service
server.port=8085

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
eureka.instance.hostname=localhost
# DÃÂÃÂÃÂÃÂ©sactiver Eureka
eureka.client.enabled=false

spring.datasource.url=jdbc:mysql://localhost:3306/cityvoice_ressource
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

stripe.secret.key=${STRIPE_SECRET_KEY}
stripe.public.key=pk_test_51TPT33CEuWTXIfk1Fp3aJtl63WFFJoZkkeTbCb8LSxkIffsF6YuKle9nwSMSLVuRUHYEjYjUF2D1XPSMEwWlLK6z00VXSPaNxU
stripe.webhook.secret=whsec_5b60e3aabc897897af88fe531d2dd42a779ce7c8c182cd742fb1a933554c2ca5
app.frontend.url=http://localhost:4200